# Generated by Django 3.2.7 on 2021-09-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
